spring.jackson.mapper.accept-case-insensitive-enums: true

logging:
  level:
    root: info
    io:
      camunda:
        process:
          test: info
    # Hide default logging from Testcontainers
    org:
      testcontainers: warn
    tc: error
    tc.camunda: warn
    tc.elasticsearch: warn
