name: Build Operate FE
description: Builds the Operate frontend

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Setup yarn
      run: npm install -g yarn
      shell: bash
    - name: Setup yarn cache
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "yarn"
        cache-dependency-path: operate/client/yarn.lock
    - name: Install node dependencies
      working-directory: ./operate/client
      shell: bash
      run: yarn
    - name: Build frontend
      working-directory: ./operate/client
      run: yarn build
      shell: bash
