name: Get Environment
description: |
  Exposes common values for consumption in conditions of other jobs in a workflow.
inputs:
  stable_branch_regex:
    description: "A bash regex provided to determine the stable branch"
    default: ^stable\/([0-9]+\.[0-9]+)$
    required: false
  main_branch_regex:
    description: "A bash regex provided to determine the main branch"
    default: ^main$
    required: false
  branch:
    description: "Defaults to github.ref_name"
    required: false
outputs:
  stable_version:
    value: ${{ steps.define-values.outputs.stable_version }}
    description: "If it's a stable branch, which stable version it is"
  is_stable_branch:
    value: ${{ steps.define-values.outputs.is_stable_branch }}
    description: "Whether the provided branch is a stable branch"
  is_main_branch:
    value: ${{ steps.define-values.outputs.is_main_branch }}
    description: "Whether the provided branch is a main branch"
  is_main_or_stable_branch:
    value: ${{ steps.define-values.outputs.is_main_or_stable_branch }}
    description: "Whether the provided branch is a main or stable branch"
  branch_slug:
    value: ${{ steps.define-values.outputs.branch_slug }}
    description: "The sanitized branch - everything lowercase and anything not a-z0-9- is replaced with -"
  git_commit_hash:
    value: ${{ steps.define-values.outputs.git_commit_hash }}
    description: "The git commit hash "
  image_tag:
    value: ${{ steps.define-values.outputs.image_tag }}
    description: "Depending on main/stable returns hash or branch-slug"
  latest_tag:
    value: ${{ steps.define-values.outputs.latest_tag }}
    description: "If stable returns stable-version-latest else latest"

runs:
  using: composite
  steps:
    - name: Get environment values
      id: define-values
      shell: bash
      run: |
        ${{ github.action_path }}/env.sh
      env:
        branch: ${{ inputs.branch || github.ref_name }}
        stable_branch_regex: ${{ inputs.stable_branch_regex }}
        main_branch_regex: ${{ inputs.main_branch_regex }}
