springfox.documentation.swagger.v2.path: /documentation
camunda.tasklist:
  elasticsearch:
    clusterName: elasticsearch
    url: http://localhost:9200
  zeebe:
    brokerContactPoint: localhost:26500
  zeebeElasticsearch:
    clusterName: elasticsearch
    url: http://localhost:9200
    prefix: zeebe-record
