springfox.documentation.swagger.v2.path: /documentation
camunda.operate:
  elasticsearch:
    clusterName: elasticsearch
    url: http://elasticsearch:9200
  zeebe:
    brokerContactPoint: zeebe:26500
  zeebeElasticsearch:
    clusterName: elasticsearch
    url: http://elasticsearch:9200
    prefix: zeebe-record