name: "Run Cross component test suite"
description: "A Github action to run E2E tests"

inputs:
  version:
    description: "C8 version"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      shell: bash
      run: npm i

    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps ${{ inputs.project }}
    - name: Set minor version
      shell: bash
      run: |
        c8_version="${{ github.event.inputs.c8Version }}"
        minor_version=${c8_version}
        echo "minor_version=$minor_version" >> $GITHUB_ENV
    - name: Run tests
      shell: bash
      env:
        CLUSTER_VERSION: ${{ inputs.version }}
        MINOR_VERSION: ${{ env.minor_version }}
      run: npm run test -- --project=${{ inputs.project }}
