springfox.documentation.swagger.v2.path: /documentation
camunda.operate:
  elasticsearch:
    clusterName: docker-cluster
    host: localhost
    port: 9200
  opensearch:
    clusterName: opensearch-cluster
    host: localhost
    port: 9200
  zeebe:
    gatewayAddress: localhost:26500
  zeebeElasticsearch:
    clusterName: docker-cluster
    host: localhost
    port: 9200
    prefix: zeebe-record
  zeebeOpensearch:
    clusterName: opensearch-cluster
    host: localhost
    port: 9200
    prefix: zeebe-record
