zeebe.broker.exporters.elasticsearch:
  className: io.camunda.zeebe.exporter.ElasticsearchExporter
  args:
    url: http://elasticsearch:9200
    bulk:
      size: 1
    index:
      processMessageSubscription: true
