name: C8 Self-Managed With Helm Manual Preview Environment - MT

on:
  workflow_dispatch:
    inputs:
      helmRepositoryBranchName:
        description: 'Branch Name in the Helm Repository'
        required: true
      helmRepositoryDirName:
        description: 'Directory in the Helm Repository'
        required: true
      zeebeVersion:
        description: 'Zeebe Version'
        required: true
      tasklistVersion:
        description: 'Tasklist Version'
        required: true
      operateVersion:
        description: 'Operate Version'
        required: true
      webModelerVersion:
        description: 'Web Modeler Version'
        required: true
      consoleVersion:
        description: 'Console Version'
        required: false
      identityVersion:
        description: 'Identity Version'
        required: true
      connectorsVersion:
        description: 'Connectors Version'
        required: true
      optimizeVersion:
        description: 'Optimize Version'
        required: true

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  init:
    name: Template Helm chart values
    runs-on: ubuntu-latest
    outputs:
      values: ${{ steps.template.outputs.values }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Template values
        id: template
        uses: ./.github/actions/template-helm-chart-values
        with:
          E2E_TESTS_CAMUNDA_HELM_DIR: "${{ github.event.inputs.helmRepositoryDirName }}"
          E2E_TESTS_KEYCLOAK_CLIENTS_SECRET: "${{ vars.DISTRO_QA_E2E_TESTS_KEYCLOAK_CLIENTS_SECRET }}"
          E2E_TESTS_IDENTITY_FIRSTUSER_PASSWORD: "${{ vars.DISTRO_QA_E2E_TESTS_IDENTITY_FIRSTUSER_PASSWORD }}"
          E2E_TESTS_IDENTITY_SECONDUSER_PASSWORD: "${{ vars.DISTRO_QA_E2E_TESTS_IDENTITY_SECONDUSER_PASSWORD }}"
          E2E_TESTS_IDENTITY_THIRDUSER_PASSWORD: "${{ vars.DISTRO_QA_E2E_TESTS_IDENTITY_THIRDUSER_PASSWORD }}"
          E2E_TESTS_IDENTITY_IMAGE_TAG: "${{ github.event.inputs.identityVersion }}"
          E2E_TESTS_CONNECTORS_IMAGE_TAG: "${{ github.event.inputs.connectorsVersion }}"
          E2E_TESTS_CONSOLE_IMAGE_TAG: "${{ github.event.inputs.consoleVersion }}"
          E2E_TESTS_OPERATE_IMAGE_TAG: "${{ github.event.inputs.operateVersion }}"
          E2E_TESTS_OPTIMIZE_IMAGE_TAG: "${{ github.event.inputs.optimizeVersion }}"
          E2E_TESTS_TASKLIST_IMAGE_TAG: "${{ github.event.inputs.tasklistVersion }}"
          E2E_TESTS_WEBMODELER_IMAGE_TAG: "${{ github.event.inputs.webModelerVersion }}"
          E2E_TESTS_ZEEBE_IMAGE_TAG: "${{ github.event.inputs.zeebeVersion }}"

  helm-deploy:
    needs: init
    name: Helm chart Integration Tests
    uses: camunda/camunda-platform-helm/.github/workflows/test-integration-template.yaml@main
    secrets: inherit
    with:
      infra-type: standard
      camunda-helm-git-ref: ${{ github.event.inputs.helmRepositoryBranchName }}
      identifier: qa-e2e-${{ github.run_id }}
      camunda-helm-dir: ${{ github.event.inputs.helmRepositoryDirName }}
      deployment-ttl: 2d
      test-enabled: false
      extra-values: |
        ${{ needs.init.outputs.values }}

  get-url:
    name: Get Test URL
    needs: helm-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set Output URL
        id: set-url
        run: echo "TEST URL = https://gke-qa-e2e-${{ github.run_id }}.ci.distro.ultrawombat.com/"
