name: Login to Harbor Registry
description: |
  Local action to simplify login to the Harbor registry
inputs:
  secrets:
    description: JSON wrapped secrets for easier secret passing
    required: true
  env:
    description: Environment prefix, e.g. "dev." or "stage."
    required: false
    default: ''
runs:
  using: composite
  steps:
  - name: Import secrets
    id: secrets
    uses: hashicorp/vault-action@8b7eaceb79bd7be97b311993e7c1cc5d051213c7
    with:
      url: ${{ fromJSON(inputs.secrets).VAULT_ADDR }}
      method: approle
      roleId: ${{ fromJSON(inputs.secrets).VAULT_ROLE_ID }}
      secretId: ${{ fromJSON(inputs.secrets).VAULT_SECRET_ID }}
      secrets: |
        secret/data/products/optimize/ci/optimize NEXUS_USERNAME;
        secret/data/products/optimize/ci/optimize NEXUS_PASSWORD;
  - name: Login to Harbor docker registery
    uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
    with:
      registry: ${{ inputs.env }}registry.camunda.cloud
      username: ${{ steps.secrets.outputs.NEXUS_USERNAME }}
      password: ${{ steps.secrets.outputs.NEXUS_PASSWORD }}
