---
zeebe:
  host: 0.0.0.0
  log:
    level: debug
  broker:
    cluster:
      partitionsCount: 2
    backpressure:
      enabled: false
    exporters:
      optimize:
        className: ${ZEEBE_EXPORTER_CLASS_NAME:io.camunda.zeebe.exporter.ElasticsearchExporter}
        args:
          url: "${DATABASE_URL:http://elasticsearch}:${DATABASE_PORT:9200}"
          index:
            prefix: zeebe-record
            createTemplate: true
            command: false
            commandDistribution: false
            decision: true
            decisionEvaluation: true
            decisionRequirements: true
            deploymentDistribution: true
            event: true
            escalation: true
            rejection: true
            deployment: true
            process: true
            error: true
            incident: true
            job: true
            jobBatch: true
            message: true
            messageSubscription: true
            signal: true
            signalSubscription: true
            timer: true
            userTask: true
            variable: true
            variableDocument: true
            processInstance: true
            processInstanceCreation: true
            processMessageSubscription: true
            processInstanceModification: true
            bulkSize: 1
