name: 'Nightly c8Run distro E2E Test Run - Mac'
description: 'A Github action to run c8Run distro E2E tests and publish results'

inputs:
  project:
    description: 'Chromium, Firefox, or Edge'
    required: true
  version:
    description: 'C8 version'
    required: true
  testrail_qa_email:
    description: 'TestRail QA email'
    required: true
  testrail_qa_key:
    description: 'TestRail QA key'
    required: true
  slack_webhook_url:
    description: 'Slack webhook url'
    required: true
  c8run_connectors_api_url:
    description: 'Connectors api url'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps ${{ inputs.project }}

    - name: Python setup
      if: always()
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Set minor version
      shell: bash
      run: |
        version="${{ inputs.version }}"
        echo "Input version: $version"
        echo "minor_version=$version" >> $GITHUB_ENV

    - name: Set OS environment variable
      shell: bash
      run: echo "OS=Mac" >> $GITHUB_ENV

    - name: Run tests
      shell: bash
      env:
        CLUSTER_VERSION: ${{ inputs.version }}
        MINOR_VERSION: ${{ env.minor_version }}
        C8RUN_CONNECTORS_API_URL: ${{ inputs.c8run_connectors_api_url  }}
        INCLUDE_SLACK_REPORTER: true
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
      run: npm run test -- --project=${{ inputs.project }}

    - name: Publish test results to TestRail
      if: always()
      shell: bash
      env:
        TESTRAIL_HOST: 'https://camunda.testrail.com/'
        TESTRAIL_USERNAME: ${{ inputs.testrail_qa_email }}
        TESTRAIL_KEY: ${{ inputs.testrail_qa_key }}
        JUNIT_RESULTS_FILE: './test-results/junit-report.xml'
        INCLUDE_SLACK_REPORTER: true
      run: |
        pip install trcli
        trcli -y -h $TESTRAIL_HOST \
          --project 'C8' \
          --username $TESTRAIL_USERNAME \
          --key $TESTRAIL_KEY \
          parse_junit --title "c8Run Nightly Test Results - Mac - $(date '+%Y-%m-%d %H:%M:%S')" \
          --close-run \
          -f $JUNIT_RESULTS_FILE
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Playwright Report
        path: ./html-report
        retention-days: 30
