#Default helm chart values
#Used for testing patch branches
identity:
  firstUser:
    existingSecret: null
    user: demo
    password: ${DISTRO_QA_E2E_TESTS_IDENTITY_FIRSTUSER_PASSWORD}
  env:
    - name: KEYCLOAK_CLIENTS_2_ID
      value: venom
    - name: KEYCLOAK_CLIENTS_2_NAME
      value: Venom
    - name: KEYCLOAK_CLIENTS_2_SECRET
      valueFrom:
        secretKeyRef:
          name: integration-test-credentials
          key: identity-admin-client-password
    - name: KEYCLOAK_CLIENTS_2_REDIRECT_URIS_0
      value: /dummy
    - name: KEYCLOAK_CLIENTS_2_ROOT_URL
      value: http://dummy
    - name: KEYCLOAK_CLIENTS_2_TYPE
      value: CONFIDENTIAL
    # Identity access.
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_0_RESOURCE_SERVER_ID
      value: camunda-identity-resource-server
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_0_DEFINITION
      value: read
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_1_RESOURCE_SERVER_ID
      value: camunda-identity-resource-server
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_1_DEFINITION
      value: write
    # Operate access.
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_2_RESOURCE_SERVER_ID
      value: operate-api
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_2_DEFINITION
      value: "read:*"
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_3_RESOURCE_SERVER_ID
      value: operate-api
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_3_DEFINITION
      value: "write:*"
    # Tasklist access.
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_4_RESOURCE_SERVER_ID
      value: tasklist-api
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_4_DEFINITION
      value: "read:*"
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_5_RESOURCE_SERVER_ID
      value: tasklist-api
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_5_DEFINITION
      value: "write:*"
    # Optimize access.
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_6_RESOURCE_SERVER_ID
      value: optimize-api
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_6_DEFINITION
      value: "write:*"
    # Zeebe access.
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_7_RESOURCE_SERVER_ID
      value: zeebe-api
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_7_DEFINITION
      value: "write:*"
    # WebModeler access.
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_8_RESOURCE_SERVER_ID
      value: web-modeler-api
    - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_8_DEFINITION
      value: "write:*"
    - name: KEYCLOAK_CLIENTS_3_ID
      value: test
    - name: KEYCLOAK_CLIENTS_3_NAME
      value: Test
    - name: KEYCLOAK_CLIENTS_3_SECRET
      value: ${DISTRO_QA_E2E_TESTS_KEYCLOAK_CLIENTS_SECRET}
    - name: KEYCLOAK_CLIENTS_3_REDIRECT_URIS_0
      value: /dummy
    - name: KEYCLOAK_CLIENTS_3_ROOT_URL
      value: http://dummy
    - name: KEYCLOAK_CLIENTS_3_TYPE
      value: CONFIDENTIAL
    # Identity access.
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_0_RESOURCE_SERVER_ID
      value: camunda-identity-resource-server
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_0_DEFINITION
      value: read
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_1_RESOURCE_SERVER_ID
      value: camunda-identity-resource-server
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_1_DEFINITION
      value: write
    # Operate access.
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_2_RESOURCE_SERVER_ID
      value: operate-api
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_2_DEFINITION
      value: "read:*"
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_3_RESOURCE_SERVER_ID
      value: operate-api
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_3_DEFINITION
      value: "write:*"
    # Tasklist access.
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_4_RESOURCE_SERVER_ID
      value: tasklist-api
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_4_DEFINITION
      value: "read:*"
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_5_RESOURCE_SERVER_ID
      value: tasklist-api
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_5_DEFINITION
      value: "write:*"
    # Optimize access.
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_6_RESOURCE_SERVER_ID
      value: optimize-api
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_6_DEFINITION
      value: "write:*"
    # Zeebe access.
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_7_RESOURCE_SERVER_ID
      value: zeebe-api
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_7_DEFINITION
      value: "write:*"
    # WebModeler access.
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_8_RESOURCE_SERVER_ID
      value: web-modeler-api
    - name: KEYCLOAK_CLIENTS_3_PERMISSIONS_8_DEFINITION
      value: "write:*"