name: C8 Run Smoke Test Run on Linux

on: push

jobs:
  build_c8run:
    name: Build and run the C8Run mac package
    runs-on: ubuntu-latest
    steps:
      - name: disable and stop mono-xsp4.service
        run: |
          sudo systemctl stop mono-xsp4.service || true
          sudo systemctl disable mono-xsp4.service || true
          sudo killall mono || true
          sudo killall xsp4 || true

      - name: checkout camunda repo
        uses: actions/checkout@v4

      - name: print architecture
        run: arch

      - name: make a package
        run: ./package.sh
        working-directory: ./c8run

      - name: Linux - Run c8run
        run: nohup ./start.sh --detached &
        working-directory: ./c8run
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-21-jdk-amd64
          JAVA_VERSION: 21.0.4

      - name: Sleep 2 mins
        run: sleep 120

      - name: Wait for camunda process to start
        run: bash -c 'while ! curl -s -f "http://localhost:8080/operate/login"; do sleep 5; done'
        timeout-minutes: 5

      - name: checkout e2e repo
        uses: actions/checkout@v4
        with:
          repository: camunda/c8-cross-component-e2e-tests
          path: c8-cross-component-e2e-tests

      - name: Run tests
        uses: ./c8-cross-component-e2e-tests/.github/actions/run-tests-c8Run

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: c8-run-logs
          path: ./camunda/c8run/log/*.log
          retention-days: 10
