---
name: Check for PR conflicts

on:
  schedule:
  - cron: 23 1 * * 1-5
  workflow_dispatch:
  pull_request:

jobs:
  check-all-pr-conflicts:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: Check all PRs for conflict
      uses: camunda/infra-global-github-actions/preview-env/conflicts@main
  check-single-pr-conflict:
    # No check on label `deploy-preview` here, because it wouldn't run
    # if there's a remaining merge conflict. Thus, only a cleanup can happen here.
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check PR for merge conflicts
      uses: camunda/infra-global-github-actions/preview-env/conflicts@main
      with:
        pull-request-id: ${{ github.event.pull_request.number }}
