name: Operate Run Test Migrate Elasticsearch Data
on:
  push:
    branches:
      - stable/8.6
    paths:
      - '.github/workflows/operate-*'
      - 'operate/**'
jobs:
  run-migration-tests:
    uses: ./.github/workflows/operate-run-tests.yml
    with:
      command: mvn -B -pl operate/qa/migration-tests/migration-test -DskipChecks -DskipTests=false verify
    secrets: inherit
