name: Operate Run Test Migrate Elasticsearch Data
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
jobs:
  run-migration-tests:
    uses: ./.github/workflows/operate-run-tests.yml
    with:
      command: ./mvnw -B -pl operate/qa/migration-tests/migration-test -DskipChecks -DskipTests=false verify
    secrets: inherit
