name: Operate Update Browserlist DB
on:
  schedule:
    - cron: "0 10 * * MON"

jobs:
  update:
    name: "Update"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: operate/client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: operate/client/yarn.lock
      - run: npx update-browserslist-db@latest --yes
        name: Update DB
      - uses: stefanzweifel/git-auto-commit-action@c86fa26bedab90b9a250e22f66759c0c50699f15
        with:
          commit_message: "chore: Update Browserlist DB"
