# TODO: Remove this pipeline once Optimize inherits from zeebe-parent,
#       with https://github.com/camunda/camunda/issues/22271
name: Optimize Checkstyle
env:
  JAVA_VERSION: "21"
on:
  push:
    branches:
      - main
  pull_request: { }
  merge_group: { }
  workflow_dispatch: { }
  workflow_call: { }
jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Java
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
        with:
          distribution: "adopt"
          java-version: "21"
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/github.com/organizations/camunda NEXUS_USR;
            secret/data/github.com/organizations/camunda NEXUS_PSW;
      - name: Setup Maven
        uses: ./.github/actions/setup-maven-dist
        with:
          maven-version: 3.8.8
          set-mvnw: true
      - name: Configure Maven
        uses: ./.github/actions/setup-maven-cache
        with:
          maven-cache-key-modifier: optimize
      - name: "Create settings.xml"
        uses: s4u/maven-settings-action@7802f6aec16c9098b4798ad1f1d8ac75198194bd # v3.0.0
        with:
          githubServer: false
          servers: |
            [{
               "id": "camunda-nexus",
               "username": "${{ steps.secrets.outputs.NEXUS_USR }}",
               "password": "${{ steps.secrets.outputs.NEXUS_PSW }}"
             }]
          mirrors: '[{"url": "https://repository.nexus.camunda.cloud/content/groups/internal/", "id": "camunda-nexus", "mirrorOf": "*", "name": "camunda Nexus"}]'
      - name: Temporarily inherit from zeebe-parent
        run: |
          sed -i -e '/<groupId>io.camunda.optimize<\/groupId>/{
              s/.*/  <parent>/;
              a\
              <groupId>io.camunda</groupId>\
              <artifactId>zeebe-parent</artifactId>\
              <version>8.7.0-SNAPSHOT</version>\
              <relativePath>../parent/pom.xml</relativePath>\
            </parent>\
            <groupId>io.camunda.optimize</groupId>
          }' optimize/pom.xml
      - name: Run checkstyle
        run: ./mvnw -f optimize/pom.xml checkstyle:check
