---
name: Preview Environment Build and Deploy

on:
  pull_request:
    types: [labeled, synchronize]

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Deploy Preview Environment C8SM
    env:
      BRANCH_NAME: ${{ github.head_ref }} # head_ref = branch on PR

    steps:
      #########################################################################
      # Sanitize the branch name to remove dependabot/,renovate/ and transform the name
      - id: sanitize
        uses: camunda/infra-global-github-actions/sanitize-branch-name@main
        with:
          branch: ${{ env.BRANCH_NAME }}
          max_length: '15'

      #########################################################################
      # Setup: import secrets from vault
      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/camunda/ci/camunda ARGOCD_DEV_TOKEN;

      #########################################################################
      # Setup: checkout code. This is required because we are using
      # composite actions and deployment manifests.
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: "Read Java / Version Info"
        id: pom-info
        uses: YunaBraska/java-info-action@main

      #########################################################################
      # Determine the argocd arguments that need to be passed to the create app command
      - name: Determine Argocd Arguments for c8sm
        shell: bash
        run: |
          echo "argocd_arguments=--dest-namespace ${app_name} \
            --file .ci/preview-environments/argo/c8sm.yml \
            --helm-set global.ingress.host=${app_url} \
            --helm-set global.identity.auth.publicIssuerUrl=https://${app_url}/auth/realms/camunda-platform \
            --helm-set global.identity.auth.operate.redirectUrl=https://${app_url}/operate \
            --helm-set global.identity.auth.tasklist.redirectUrl=https://${app_url}/tasklist \
            --helm-set global.identity.auth.optimize.redirectUrl=https://${app_url}/optimize \
            --helm-set global.identity.auth.webModeler.redirectUrl=https://${app_url}/modeler \
            --helm-set global.identity.auth.console.redirectUrl=https://${app_url}/console \
            --helm-set global.identity.auth.connectors.redirectUrl=https://${app_url}/connectors \
            --helm-set camunda-platform.identity.fullURL=https://${app_url}/identity \
            --helm-set camunda-platform.zeebeGateway.ingress.grpc.host=zeebe-${app_url} \
            --name ${app_name} \
            --revision ${revision} \
            --helm-set git.branch=${revision} \
            --upsert" >> $GITHUB_ENV
        env:
          docker_tag: "pr-${{ github.event.pull_request.head.sha }}"
          revision: ${{ env.BRANCH_NAME }}
          app_name: camunda-${{ steps.sanitize.outputs.branch_name }}
          app_url: ${{ steps.sanitize.outputs.branch_name }}.camunda.camunda.cloud

      #########################################################################
      # Create a preview environment
      - name: Deploy Preview Environment for c8sm
        uses: camunda/infra-global-github-actions/preview-env/create@main
        with:
          revision: ${{ env.BRANCH_NAME }}
          argocd_token: ${{ steps.secrets.outputs.ARGOCD_DEV_TOKEN }}
          app_name: camunda-${{ steps.sanitize.outputs.branch_name }}
          app_url: https://${{ steps.sanitize.outputs.branch_name }}.camunda.camunda.cloud
          argocd_arguments: ${{ env.argocd_arguments }}
          argocd_server: dev.argocd.int.camunda.com

  comment:
    if: always() && needs.deploy-preview.result != 'skipped' && needs.deploy-preview.result != 'cancelled'
    name: Create Deployment Result Summary Comment
    runs-on: ubuntu-latest
    needs: [deploy-preview]
    steps:
      - uses: camunda/infra-global-github-actions/preview-env/comment@main

  clean:
    if: always() && needs.deploy-preview.result != 'skipped' && needs.deploy-preview.result != 'cancelled'
    name: Clean Preview Environment
    needs: [deploy-preview]
    uses: camunda/camunda/.github/workflows/preview-env-clean.yml@preview-env-build-helmchart
    secrets: inherit
    with:
      pull-request: ${{ github.event.pull_request.number }}
