name: Vacuum OpenAPI lint
on:
  pull_request:
    paths:
      - 'zeebe/gateway-protocol/src/main/proto/rest-api.yaml'

jobs:
  lint-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Vacuum
        run: curl -fsSL https://quobix.com/scripts/install_vacuum.sh | sh > /dev/null
        shell: bash
      - name: Run OpenAPI Linter
        run: vacuum lint zeebe/gateway-protocol/src/main/proto/rest-api.yaml -r .github/vacuum-ruleset.yaml -d -e 
        shell: bash
