name: GraalVM build
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        os: [ macos, windows, linux ]
        include:
          - os: macos
            runner: macos-latest
          - os: windows
            runner: windows-latest
          - os: linux
            runner: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Package zbctl
        run: mvn package -DskipTests -DskipChecks -DskipUpx=false -am -pl clients/zbctl -Pnative
      - name: Upload zbctl
        uses: actions/upload-artifact@v3
        with:
          name: zbctl-${{ matrix.os }}
          path: |
            clients/zbctl/target/zbctl

