name: Start a Zeebe test in Testbench

on:
  workflow_call:
    inputs:
      variables:
        description: 'Process instance variables'
        required: true
        type: string
      processId:
        description: 'Id of process to start in testbench (eg:- e2e-testbench-protocol)'
        required: true
        type: string
      branch:
        description: 'Branch to test'
        required: true
        type: string

jobs:
  testbench:
    name: Start a test in testbench
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Authenticate for zeebe image registry
        uses: google-github-actions/auth@v2
        id: auth-zeebe
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/628707732411/locations/global/workloadIdentityPools/zeebe-gh-actions/providers/gha-provider'
          service_account: 'zeebe-gh-actions@zeebe-io.iam.gserviceaccount.com'
      - name: Authenticate for saas image registry
        id: auth-saas
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/618877442292/locations/global/workloadIdentityPools/github/providers/camunda'
          service_account: 'github-actions@camunda-saas-registry.iam.gserviceaccount.com'
      - name: Setup BuildKit
        uses: docker/setup-buildx-action@v3
      - name: Login to SaaS image registry
        uses: docker/login-action@v3
        with:
          registry: europe-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth-saas.outputs.access_token }}
      - name: Login to Zeebe image registry
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: oauth2accesstoken
<<<<<<< HEAD
          password: ${{ steps.auth.outputs.access_token }}
=======
          password: ${{ steps.auth-zeebe.outputs.access_token }}
      - uses: ./.github/actions/setup-zeebe
        with:
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
>>>>>>> 8aa65ec5 (ci: push testbench images to SaaS registry)
      - id: image-tag
        name: Calculate image tag
        shell: bash
        run: |
          # Replace dots and slashes with dashes
          branch=${BRANCH/[\/\.]/-}
          version=$(mvn help:evaluate -q -DforceStdout -D"expression=project.version")
          echo "image-tag=$version-$branch-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        env:
          BRANCH: ${{ inputs.branch }}
      - uses: ./.github/actions/setup-zeebe
        with:
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
      - uses: ./.github/actions/build-zeebe
        id: build-zeebe
      - uses: ./.github/actions/build-zeebe-docker
        id: build-zeebe-docker
        with:
          repository: europe-docker.pkg.dev/camunda-saas-registry/zeebe/zeebe
          version: ${{ steps.image-tag.outputs.image-tag }}
          push: true
          distball: ${{ steps.build-zeebe.outputs.distball }}
      - name: Build and Push Starter Image
        run: ./mvnw -pl benchmarks/project jib:build -P starter -D image="gcr.io/zeebe-io/starter:${{ steps.image-tag.outputs.image-tag }}"
      - name: Build and Push Worker Image
        run: ./mvnw -pl benchmarks/project jib:build -P worker -D image="gcr.io/zeebe-io/worker:${{ steps.image-tag.outputs.image-tag }}"
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.7.5
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/zeebe/ci/zeebe TESTBENCH_PROD_CLIENT_SECRET;
            secret/data/products/zeebe/ci/zeebe TESTBENCH_PROD_CONTACT_POINT;
      - name: Start Test
        shell: bash
        run: |
          chmod +x clients/go/cmd/zbctl/dist/zbctl
          variables=$(echo "${{ inputs.variables }}" | envsubst)
          clients/go/cmd/zbctl/dist/zbctl create instance ${{ inputs.processId }} --variables "$variables"
        env:
          IMAGE: ${{ steps.build-zeebe-docker.outputs.image }}
          ZEEBE_CLIENT_SECRET: ${{ steps.secrets.outputs.TESTBENCH_PROD_CLIENT_SECRET }}
          ZEEBE_ADDRESS: ${{ steps.secrets.outputs.TESTBENCH_PROD_CONTACT_POINT }}
          ZEEBE_AUTHORIZATION_SERVER_URL: 'https://login.cloud.camunda.io/oauth/token'
          ZEEBE_CLIENT_ID: 'Jg9caDRuAWHchvM7JiaVlndL-qVFfp~0'
